// Simplified Chinese → Japanese kanji
// Only pairs where the forms actually differ and appear in sake names / place names
const S2J = {
  // Sake / brewing vocabulary
  '产': '産',  // 産地, 特産
  '酿': '醸',  // 醸造, 醸し
  '纯': '純',  // 純米
  '传': '伝',  // 伝統
  // Kanji frequent in brand / brewery / place names
  '龙': '龍',  // 龍力, 黒龍 …
  '东': '東',  // 東洋美人, 東一 …
  '丰': '豊',  // 豊盃, 豊明 … (JA: 豊, not TC: 豐)
  '飞': '飛',  // 飛露喜, 飛良泉 …
  '铃': '鈴',  // 鈴木酒造 …
  '泽': '澤',  // 澤の花 …
  '岛': '島',  // 広島, 鹿児島 …
  '华': '華',  // 日本盛 華 …
  '达': '達',  // 名達 …
  '长': '長',  // 長岡, 長野 …
  '风': '風',  // 風の森 …
  '兰': '蘭',  // 蘭 …
  '荣': '栄',  // 栄光富士 … (JA: 栄, not TC: 榮)
  '丽': '麗',  // 麗峰 …
  '胜': '勝',  // 勝駒, 勝山 …
  '实': '実',  // 実り … (JA: 実, not TC: 實)
  '贵': '貴',  // 貴 …
  '义': '義',  // 義 …
  '鸟': '鳥',  // 鳥取 …
  '马': '馬',  // 馬 …
  '带': '帯',  // 帯広 … (JA: 帯, not TC: 帶)
  '门': '門',  // 水門 …
  '汉': '漢',  // 漢 …
  '间': '間',  // 間 …
  '发': '発',  // 発酵 … (JA: 発, not TC: 發)
  '单': '単',  // 単式 … (JA: 単, not TC: 單)
  '总': '総',  // 総 … (JA: 総, not TC: 總)
  '宽': '寛',  // 寛政 … (JA: 寛, not TC: 寬)
  '滨': '浜',  // 浜松, 横浜 … (JA: 浜, not TC: 濱)
  '关': '関',  // 関西 … (JA: 関, not TC: 關)
  '变': '変',  // 変 … (JA: 変, not TC: 變)
  '艺': '芸',  // 芸術 … (JA: 芸, not TC: 藝)
  '齐': '斉',  // 斉 … (JA: 斉, not TC: 齊)
  '斋': '斎',  // 斎 … (JA: 斎, not TC: 齋)
  '庄': '荘',  // 荘 … (JA: 荘, not TC: 莊)
  '渔': '漁',  // 漁 …
  '尧': '尭',  // 尭 …
  '临': '臨',  // 臨 …
  '寿': '寿',  // same in JA (壽→寿 already done by JA)
  '亚': '亜',  // 亜 … (JA: 亜, not TC: 亞)
  '来': '来',  // already same in JA — no change
}

// Convert a query string: map each simplified char to its Japanese equivalent
export function toJP(str) {
  return str.split('').map(c => S2J[c] ?? c).join('')
}

// Returns both the original and converted query (deduplicated)
export function expandQuery(str) {
  const converted = toJP(str)
  return converted === str ? [str] : [str, converted]
}
