// One-shot: overwrite bogus summaries (title-repeat) for old rice/yeast entries
// with real concise one-liners in ja / zhtw / en.
// Body_ja / body_en are already good in DB; body_zh (simplified) untouched.

import fs from 'node:fs'

const env = fs.readFileSync('.env.local', 'utf8')
const SUPABASE_URL = env.match(/VITE_SUPABASE_URL=(.+)/)[1].trim()
const SERVICE_KEY  = env.match(/SUPABASE_SERVICE_ROLE_KEY=(.+)/)[1].trim()

const rows = [
  // ── Major rice ───────────────────────────────────────────────────────
  { term_id: 'yamadanishiki',
    summary_ja: '兵庫県生まれの「酒米の王様」。心白が大きくタンパク質が少なく、繊細で上品な大吟醸に最適。',
    summary_zhtw: '兵庫縣「酒米之王」。心白大、蛋白質少，最適合細膩高雅的大吟釀，全國名蔵廣泛使用。',
    summary_en: 'The "king of sake rice," from Hyogo. Large shinpaku and low protein — ideal for elegant daiginjo.' },
  { term_id: 'gohyakumangoku',
    summary_ja: '新潟原産、生産量全国2位。淡麗辛口スタイルに向き、スッキリ透明感のある酒を生む。',
    summary_zhtw: '新潟原產，產量全國第二。適合淡麗辛口風格，能酿出清爽透明感的酒。',
    summary_en: 'Niigata-origin, #2 in national volume. Suited to lean, dry sake with clean transparency.' },
  { term_id: 'omachi',
    summary_ja: '岡山備前産の古代米。山田錦のルーツで、力強い旨味とコク・野趣ある風味が特徴。',
    summary_zhtw: '岡山備前古代米。山田錦的祖先，力強旨味與醇厚感、野性風味為特徵。',
    summary_en: 'Ancient Bizen (Okayama) variety — ancestor of Yamadanishiki. Bold umami with a wild, earthy edge.' },
  { term_id: 'dewasansan',
    summary_ja: '山形県が「山田錦超え」を目標に開発。大粒で心白発達、爽やかな甘みと上品な吟醸香。',
    summary_zhtw: '山形縣以「超越山田錦」為目標開發。大粒心白發達，清爽甘味與高雅吟釀香。',
    summary_en: 'Yamagata\'s answer to Yamadanishiki. Large grain and shinpaku, clean sweetness and refined ginjo aromas.' },
  { term_id: 'koshitanrei',
    summary_ja: '新潟が山田錦×五百万石を交配（2004年）。淡麗ながら旨味の深みを持つ中核米。',
    summary_zhtw: '新潟以山田錦×五百萬石交配（2004年）。淡麗中帶旨味深度的中堅品種。',
    summary_en: 'Niigata\'s premium cross (Yamadanishiki × Gohyakumangoku, 2004). Lean yet layered — a modern classic.' },

  // ── Regional rice ────────────────────────────────────────────────────
  { term_id: 'miyamanishiki',
    summary_ja: '長野生まれ、耐冷性に優れる。信州・東北の寒冷地で広く栽培、上品な吟醸酒向け。',
    summary_zhtw: '長野原產，耐冷性優異。信州、東北寒冷地廣泛栽培，適合高雅吟釀。',
    summary_en: 'A cold-resistant Nagano rice widely grown across Shinshu and Tohoku. Elegant, ginjo-friendly.' },
  { term_id: 'aiyama',
    summary_ja: '生産量が極めて少ない「幻の酒米」。甘み・華やかな香り・深い旨味を引き出す。',
    summary_zhtw: '產量極稀少的「夢幻酒米」。能引出甘美、華麗香氣與深厚旨味。',
    summary_en: 'The rare "phantom rice." Extremely limited output; draws out sweetness, floral aromas, and deep umami.' },
  { term_id: 'hattannishiki',
    summary_ja: '広島の代表品種。三段仕込みを生んだ広島の醸造文化と相性が良く、まろやかで豊かな酒質。',
    summary_zhtw: '廣島代表品種。契合廣島釀造文化，能酿出圓潤豐盈的酒質。',
    summary_en: 'Hiroshima\'s signature variety. Fits the region\'s brewing culture — mellow and full-bodied.' },
  { term_id: 'kamenoo',
    summary_ja: '明治期の東北古代品種。一度絶滅寸前まで衰退し復活。個性的な旨味と野趣あふれる風味。',
    summary_zhtw: '明治期東北古代品種。曾瀕臨絕種後復活，個性旨味與野性風味為魅力。',
    summary_en: 'A Meiji-era Tohoku ancient rice, nearly extinct before revival. Distinctive umami with wild character.' },
  { term_id: 'akita-sake-komachi',
    summary_ja: '秋田県が開発した高精白向け酒米。山田錦並みの大粒、上品な吟醸香と穏やかな旨味。',
    summary_zhtw: '秋田縣開發，適合高精白。粒大堪比山田錦，高雅吟釀香與溫和旨味。',
    summary_en: 'Akita\'s premium sake rice, rivaling Yamadanishiki in grain size. Elegant, floral, gently umami.' },
  { term_id: 'yukimegami',
    summary_ja: '山形県が2014年登録。出羽燦々の改良種で、繊細でフルーティーな香りと柔らかい旨味。',
    summary_zhtw: '山形縣2014年登記。出羽燦々改良種，纖細果香與柔和旨味。',
    summary_en: 'A Yamagata rice registered in 2014 — an evolution of Dewasansan. Delicate fruit aromas, soft umami.' },
  { term_id: 'hanaomoi',
    summary_ja: '福島オリジナル、山田錦の血統。大粒で心白大、華やかな吟醸香を引き出しやすい。',
    summary_zhtw: '福島原創，山田錦血統。粒大心白發達，易引出華麗吟釀香。',
    summary_en: 'Fukushima\'s Yamadanishiki-descended rice. Large grain and shinpaku — draws out floral ginjo aromas.' },
  { term_id: 'ginpu',
    summary_ja: '北海道が1997年登録。厳寒気候に適応した耐冷性、さっぱり淡麗と穏やかな旨味。',
    summary_zhtw: '北海道1997年登記。適應嚴寒氣候，清爽淡麗與溫和旨味。',
    summary_en: 'Hokkaido\'s cold-hardy sake rice (registered 1997). Clean, lean, with pleasant acidity.' },
  { term_id: 'tsuyuhakase',
    summary_ja: '奈良の在来酒米。甘みと旨味が強く、複雑な味わい。「風の森」油長酒造の代表米。',
    summary_zhtw: '奈良在來酒米。甘味與旨味強、口感複雜。「風の森」油長酒造代表米。',
    summary_en: 'A native Nara sake rice with rich sweetness and complexity. Championed by Yucho Shuzo (Kaze no Mori).' },
  { term_id: 'senbonnishiki',
    summary_ja: '広島が山田錦×中生新千本を交配。八反錦と並ぶ広島の代表品種、吟醸酒に幅広く使用。',
    summary_zhtw: '廣島以山田錦×中生新千本交配。與八反錦並列廣島代表品種，廣泛用於吟釀。',
    summary_en: 'Hiroshima\'s Yamadanishiki × Nakate Shinsenbon cross. Alongside Hattannishiki, defines modern Hiroshima ginjo.' },
  { term_id: 'tamasakae',
    summary_ja: '滋賀県育成、心白が大きく旨味が豊か。醇厚でボリューム感のある酒に向く。',
    summary_zhtw: '滋賀縣育成。心白大、旨味豐富，適合醇厚豐盈的酒。',
    summary_en: 'Bred by Shiga. Large shinpaku with rich umami — produces full-bodied, voluminous sake.' },
  { term_id: 'wakamizuki',
    summary_ja: '愛知県開発、大粒で心白発達。柔らかな旨味とふくよかな甘み。「九平次」愛用米。',
    summary_zhtw: '愛知縣開發，大粒心白發達。柔和旨味與豐盈甘味。「九平次」愛用米。',
    summary_en: 'An Aichi rice with large grain and prominent shinpaku. Soft umami and round sweetness — used by Kuheiji.' },
  { term_id: 'kinmonnishiki',
    summary_ja: '長野育成、山田錦系統。信州の冷涼気候でも安定、豊かな旨味とふくよかな甘み。',
    summary_zhtw: '長野育成，山田錦系統。信州冷涼氣候穩定生長，豐富旨味與豐盈甘味。',
    summary_en: 'A Yamadanishiki-descended Nagano rice that thrives in the cool Shinshu climate. Rich, round.' },
  { term_id: 'ipponjime',
    summary_ja: '新潟オリジナル、五百万石×山田錦。淡麗でキレのある新潟スタイルに合うスッキリ味。',
    summary_zhtw: '新潟原創，五百萬石×山田錦。契合新潟淡麗辛口風格的清爽口感。',
    summary_en: 'Niigata\'s cross of Gohyakumangoku and Yamadanishiki. Clean, crisp — a fit for Niigata\'s lean style.' },
  { term_id: 'kairyo-omachi',
    summary_ja: '雄町ベースに耐倒伏性を改良した品種。力強い旨味とコクを保ちつつ栽培しやすい。',
    summary_zhtw: '以雄町為基礎改良耐倒伏性。保有雄町的力強旨味與醇厚，栽培更容易。',
    summary_en: 'An improved Omachi with better lodging resistance. Retains Omachi\'s bold umami with easier cultivation.' },

  // ── Kyokai yeasts ────────────────────────────────────────────────────
  { term_id: 'kyokai-7',
    summary_ja: '長野・真澄蔵由来、日本最多使用の標準酵母。安定した発酵と穏やかな香り・しっかりした旨味。',
    summary_zhtw: '長野・真澄蔵由來，日本使用最廣泛的標準酵母。發酵穩定，溫和香氣與紮實旨味。',
    summary_en: 'From Nagano\'s Masumi brewery — the most widely used sake yeast in Japan. Stable, moderate aromas.' },
  { term_id: 'kyokai-9',
    summary_ja: '別名・熊本酵母。カプロン酸エチル系の華やかな吟醸香、YK35方程式で現代吟醸ブームを牽引。',
    summary_zhtw: '別名熊本酵母。己酸乙酯系華麗吟釀香，以YK35公式引領現代吟釀熱潮。',
    summary_en: 'Also called Kumamoto yeast. Rich ethyl caproate aroma — the driver of the modern ginjo boom.' },
  { term_id: 'kyokai-14',
    summary_ja: '別名・金沢酵母。バナナ・マスカット系の華やかな香り、酸控えめで食事と相性良好。',
    summary_zhtw: '別名金澤酵母。香蕉、麝香葡萄系華麗香氣，酸度低、與食物搭配性佳。',
    summary_en: 'Also called Kanazawa yeast. Banana / muscat aromas, low acid — pairs well with food.' },
  { term_id: 'kyokai-6',
    summary_ja: '秋田・新政酒造由来の最古参協会酵母。酸多め、どっしりした旨味。新政の看板酵母。',
    summary_zhtw: '秋田・新政酒造由來的最古老協會酵母。酸度高、扎實旨味。新政的招牌酵母。',
    summary_en: 'Aramasa\'s (Akita) heritage yeast — the oldest surviving Kyokai. Higher acid, deep rice umami.' },
  { term_id: 'kyokai-10',
    summary_ja: '茨城・明利酒類の「小川酵母」。全協会酵母中最も酸が少なく、繊細で華やかな吟醸香。',
    summary_zhtw: '茨城・明利酒類的「小川酵母」。所有協會酵母中酸度最低，纖細華麗吟釀香。',
    summary_en: 'The Ogawa yeast from Meiri Shurui (Ibaraki). Lowest acid of any Kyokai — delicate, floral ginjo.' },
  { term_id: 'kyokai-11',
    summary_ja: '協会7号の高アルコール環境選抜株（1975年）。高いアルコール耐性と超辛口・キレの良さ。',
    summary_zhtw: '協會7號的高酒精環境選拔株（1975年）。高酒精耐性、超辛口與清爽收尾。',
    summary_en: 'A No. 7 strain bred in 20% alcohol (1975). High alcohol tolerance, dry finish, minimal amino acids.' },
  { term_id: 'kyokai-15',
    summary_ja: '秋田酵母AK-1（1996年、1501号として頒布）。9号の約2倍のカプロン酸エチルを生成。',
    summary_zhtw: '秋田酵母AK-1（1996年頒布1501號）。己酸乙酯產量約為9號的兩倍。',
    summary_en: 'Akita\'s AK-1 (distributed as No. 1501 in 1996). ~2× the ethyl caproate of No. 9.' },
  { term_id: 'kyokai-16',
    summary_ja: '月桂冠のセルレニン耐性技術による高エステル酵母（1992年）。1801号の礎を築いた。',
    summary_zhtw: '月桂冠塞吕宁耐性技術的高酯酵母（1992年）。奠定1801號的基礎。',
    summary_en: 'A cerulenin-resistant, high-ester yeast from Gekkeikan (1992). The technical precursor to No. 1801.' },
  { term_id: 'kyokai-18',
    summary_ja: '現代の吟醸主流酵母（2006年頒布）。カプロン酸エチル豊富、リンゴ・メロン系の華やかな香り。',
    summary_zhtw: '現代吟釀主流酵母（2006年頒布）。己酸乙酯豐富，蘋果、哈密瓜系華麗香氣。',
    summary_en: 'The reigning ginjo yeast (distributed 2006). Abundant ethyl caproate — apple and melon aromas.' },
  { term_id: 'kyokai-28',
    summary_ja: '2018年頒布の新世代酵母。カプロン酸エチルと酢酸イソアミルの両方を高生産。',
    summary_zhtw: '2018年頒布的新世代酵母。同時高產己酸乙酯與乙酸異戊酯。',
    summary_en: 'A new-generation yeast distributed in 2018. Produces both ethyl caproate and isoamyl acetate at high levels.' },
  { term_id: 'kyokai-12',
    summary_ja: '愛媛「小夜衣」由来、優雅で複雑な吟醸香を持つが発酵力弱く1993年廃頒布。',
    summary_zhtw: '愛媛「小夜衣」由來，優雅複雜的吟釀香但發酵力弱，1993年廢頒布。',
    summary_en: 'From Ehime\'s Sayogoromo. Elegant, complex ginjo aroma but weak fermentation — discontinued 1993.' },
  { term_id: 'kyokai-8',
    summary_ja: '1960年頒布・1977年廃頒布の「幻の酵母」。高酸・濃醇で当時の淡麗辛口志向と合わず。',
    summary_zhtw: '1960年頒布、1977年廢頒布的「幻之酵母」。高酸濃醇，與當時淡麗辛口志向不合。',
    summary_en: 'The "phantom yeast" (1960 – 1977). High-acid, full-bodied — out of step with the tanrei-karakuchi era.' },
  { term_id: 'kyokai-1',
    summary_ja: '1906年頒布の日本初の協会酵母。灘の櫻正宗蔵由来。現在は廃頒布、記念碑的な存在。',
    summary_zhtw: '1906年頒布，日本首株協會酵母。灘・櫻正宗蔵由來。現已廢頒布，具紀念意義。',
    summary_en: 'Japan\'s first Kyokai yeast (1906) from Sakura Masamune in Nada. Discontinued — a historic milestone.' },
  { term_id: 'kyokai-3',
    summary_ja: '1914年頒布、広島・酔心由来。当時最高品質と評価されたが後継酵母に置き換わり廃頒布。',
    summary_zhtw: '1914年頒布，廣島・醉心由來。當時公認最高品質，後被繼任酵母取代廢頒布。',
    summary_en: 'Distributed 1914 from Suishin in Hiroshima. Once considered the finest — later replaced and retired.' },
  { term_id: 'kyokai-5',
    summary_ja: '1923年頒布、広島・賀茂鶴由来。7号出現前の主力酵母、現在は廃頒布。',
    summary_zhtw: '1923年頒布，廣島・賀茂鶴由來。7號出現前的主力酵母，現已廢頒布。',
    summary_en: 'Distributed 1923 from Kamotsuru in Hiroshima. A workhorse before No. 7 emerged — now discontinued.' },

  // ── Local yeasts ─────────────────────────────────────────────────────
  { term_id: 'cel24',
    summary_ja: '高知県開発、強い発泡性と高いリンゴ酸生成能力。甘口スパークリング日本酒に最適。',
    summary_zhtw: '高知縣開發，強發泡性與高蘋果酸產量。最適合甘口氣泡日本酒。',
    summary_en: 'A Kochi yeast — high carbonation and malic acid. Ideal for sweet, sparkling low-alcohol sake.' },
  { term_id: 'cel19',
    summary_ja: '高知県開発のCEL系酵母。爽やかな酸とフルーティな香り、キレの良い低アル酒に向く。',
    summary_zhtw: '高知縣開發的CEL系酵母。清爽酸味與果香，適合爽利收尾的低酒精酒。',
    summary_en: 'A Kochi CEL-line yeast with crisp acidity and fruity aromas — suited to clean, low-alcohol sake.' },
  { term_id: 'shizuoka-yeast',
    summary_ja: '静岡が独自開発、エステル類少なくクリアな発酵香。すっきりした上品な吟醸香・透明感。',
    summary_zhtw: '靜岡獨自開發。酯類少、發酵香清潔，清爽高雅吟釀香與透明感。',
    summary_en: 'Shizuoka\'s proprietary yeast. Low esters, exceptionally clean — defining the region\'s tanrei style.' },
  { term_id: 'akita-yeast',
    summary_ja: '秋田県開発のAK-1系。カプロン酸エチル豊富、華やかな吟醸香。協会1501号として全国普及。',
    summary_zhtw: '秋田縣開發的AK-1系。己酸乙酯豐富，華麗吟釀香。作為協會1501號全國普及。',
    summary_en: 'Akita\'s AK-1 line — abundant ethyl caproate, floral ginjo aromas. Distributed nationally as No. 1501.' },
  { term_id: 'yamagata-yeast',
    summary_ja: '山形が独自開発したKAシリーズ・山形酵母。上品な吟醸香とキレの良い酒質を生む。',
    summary_zhtw: '山形獨自開發的KA系列山形酵母。高雅吟釀香與爽利收尾的酒質。',
    summary_en: 'Yamagata\'s proprietary KA-series yeasts. Refined ginjo aromas with a crisp, clean finish.' },
  { term_id: 'fukushima-yeast',
    summary_ja: 'うつくしま夢酵母、うつくしま煌酵母など福島県独自の酵母群。華やか香りと繊細な味わい。',
    summary_zhtw: 'うつくしま夢酵母、うつくしま煌酵母等福島縣獨自酵母群。華麗香氣與纖細口感。',
    summary_en: 'Fukushima\'s proprietary yeasts (Yume, Kirameki lines). Floral aromas with delicate character.' },
  { term_id: 'hiroshima-yeast',
    summary_ja: '広島酵母（もみじ酵母など）。広島の吟醸文化を支える、華やかで上品な香り系酵母。',
    summary_zhtw: '廣島酵母（紅葉酵母等）。支撐廣島吟釀文化，華麗高雅香氣系酵母。',
    summary_en: 'Hiroshima\'s yeasts (Momiji, etc). Floral, refined — the foundation of Hiroshima\'s ginjo tradition.' },
  { term_id: 'niigata-yeast',
    summary_ja: '新潟G9・TK-8など、淡麗辛口スタイルに適した新潟県独自酵母。穏やかな香りとキレ。',
    summary_zhtw: '新潟G9、TK-8等，適合淡麗辛口風格的新潟縣獨自酵母。溫和香氣與爽利收尾。',
    summary_en: 'Niigata\'s G9, TK-8 and related strains — bred for the region\'s lean, dry style. Restrained aromas, clean finish.' },
  { term_id: 'uchu-yeast',
    summary_ja: '2005年ISSに10日間滞在した高知の宇宙酵母。世界初「宇宙酒」を実現、司牡丹など参加。',
    summary_zhtw: '2005年在ISS停留10天的高知宇宙酵母。實現世界首款「宇宙酒」，司牡丹等參與。',
    summary_en: 'Kochi\'s yeast that spent 10 days on the ISS in 2005 — created the world\'s first "space sake." Featured by Tsukasabotan.' },
  { term_id: 'hana-kobo',
    summary_ja: '東京農業大学が花から分離した酵母群（40種以上）。花本来の香りではなく洋梨・リンゴ系。',
    summary_zhtw: '東京農業大學從花朵分離的酵母群（40餘種）。並非花的香氣，而是洋梨、蘋果系果香。',
    summary_en: 'A family of yeasts isolated from flowers by Tokyo Univ. of Agriculture (40+ varieties). Notes lean pear/apple, not floral.' },
]

;(async () => {
  console.log(`Updating summaries for ${rows.length} entries...`)
  let ok = 0, fail = 0
  for (const r of rows) {
    const res = await fetch(`${SUPABASE_URL}/rest/v1/wiki_articles?term_id=eq.${r.term_id}`, {
      method: 'PATCH',
      headers: {
        apikey: SERVICE_KEY,
        Authorization: `Bearer ${SERVICE_KEY}`,
        'Content-Type': 'application/json',
        Prefer: 'return=minimal',
      },
      body: JSON.stringify({
        summary_ja: r.summary_ja,
        summary_zhtw: r.summary_zhtw,
        summary_en: r.summary_en,
        // Also clear old summary_zh (which was just a title-repeat)
        summary_zh: null,
        updated_at: new Date().toISOString(),
      }),
    })
    if (res.ok) { ok++; process.stdout.write('.') }
    else { fail++; console.error(`\n! ${r.term_id}: ${res.status} ${await res.text()}`) }
  }
  console.log(`\n✓ ${ok} updated, ${fail} failed`)
})()
