#!/usr/bin/env node
import { createClient } from '@supabase/supabase-js'

const db = createClient(
  'https://iqfgzxbwthdybokvafsi.supabase.co',
  process.env.SUPABASE_SERVICE_ROLE_KEY ?? '',
)

const articles = [
  {
    term_id: 'junmai',
    summary_ja: '醸造アルコール無添加。米・米麹・水のみで醸す純粋な日本酒。米本来の旨味とコクが豊か。',
    summary_zh: '不添加酿造酒精，仅以米、米麴、水酿成。米本身的旨味与醇厚感突出。',
    summary_en: 'Brewed from rice, koji, and water only — no added alcohol. Rich, full-bodied, and true to the grain.',
    body_ja: '醸造アルコールを一切添加せず、米・米麹・水だけで醸した日本酒。米本来の旨味・コクが出やすく、燗酒でも美味しい。純米酒は精米歩合の規定がないため、蔵元の個性が反映されやすい。吟醸・大吟醸・本醸造などと組み合わせて「純米吟醸」「純米大吟醸」と表記する場合もある。',
    body_zh: '不添加酿造酒精，仅以米、米麴、水酿成的日本酒。米本身的旨味和醇厚感明显，热饮风味也佳。纯米酒对精米步合无硬性规定，充分体现各酒厂的酿造哲学。也可与吟酿、大吟酿组合，标注为"纯米吟酿""纯米大吟酿"。',
    body_en: 'Sake brewed from only rice, koji, and water — no added alcohol. Rich, full-bodied, and often excellent warm. Unlike ginjo grades, junmai has no polishing ratio requirement, giving brewers creative freedom. It may be combined with ginjo or daiginjo designations (e.g. Junmai Ginjo, Junmai Daiginjo).',
  },
  {
    term_id: 'ginjo',
    summary_ja: '精米歩合60%以下、低温長期発酵。吟醸造りによる華やかな果実系の香り（吟醸香）が特徴。',
    summary_zh: '精米步合60%以下，低温缓慢发酵，以华丽的果香（吟酿香）为特征。',
    summary_en: 'Rice polished to ≤60%, fermented slowly at low temperatures. Known for its signature fruity "ginjo" aroma.',
    body_ja: '精米歩合60%以下の米を使い、低温でゆっくり発酵させた日本酒。華やかな果実香（吟醸香）が特徴。吟醸造りは手間と時間がかかるため、価格帯は高め。醸造アルコールを添加したものは「吟醸」、添加しないものは「純米吟醸」と区別される。提供温度は冷やして飲むのが一般的。',
    body_zh: '使用精米步合60%以下的米，低温缓慢发酵。以华丽的果香（吟酿香）为特征。吟酿酿造工艺繁琐耗时，价格偏高。添加酿造酒精的称"吟酿"，不添加的称"纯米吟酿"。通常冷饮最佳。',
    body_en: 'Sake made from rice polished to at least 60%, fermented slowly at low temperatures. Known for its fruity "ginjo aroma" (吟醸香). The process is labor-intensive and time-consuming, so ginjo-grade sake tends to be pricier. If no alcohol is added, it becomes Junmai Ginjo. Best served chilled.',
  },
  {
    term_id: 'daiginjo',
    summary_ja: '精米歩合50%以下の高精白米で醸す、吟醸酒の最高峰。繊細かつエレガントな香味が魅力。',
    summary_zh: '精米步合50%以下，是吟酿中的最高级别。细腻优雅的香气与口感为其魅力所在。',
    summary_en: 'The pinnacle of ginjo — polished to ≤50%. Exceptionally delicate, elegant aromas and a refined palate.',
    body_ja: '精米歩合50%以下という高精白の米を使った日本酒。吟醸の中でも最高クラス。繊細でエレガントな香りと味わいが魅力。米の外側を50%以上削るため、コストが高く製造に高い技術が求められる。コンクールでの受賞酒も多く、贈答品としても人気。',
    body_zh: '使用精米步合50%以下高精白米酿造，是吟酿中的最高级别。以细腻优雅的香气和口感为特征。因去除米外侧50%以上，成本高、工艺要求高。常见于各类评酒赛获奖酒款，也是受欢迎的赠礼选择。',
    body_en: 'The premium tier of ginjo, polished to 50% or less. Delicate, elegant aromas with a refined finish. Achieving this level requires removing more than half the grain, demanding exceptional skill and cost. Many award-winning sakes are daiginjo, and they are popular as gifts.',
  },
  {
    term_id: 'honjozo',
    summary_ja: '醸造アルコールを少量添加（白米重量の10%以下）した日本酒。軽快でスッキリした飲み口。',
    summary_zh: '少量添加酿造酒精（≤白米重量10%）。口感轻快清爽，易于饮用。',
    summary_en: 'A small addition of distilled alcohol (≤10% of rice weight). Light, crisp, and very easy-drinking.',
    body_ja: '醸造アルコールを少量添加した日本酒。添加量は白米重量の10%以下と規定されている。軽快でスッキリした飲み口。アルコール添加によって香りが引き立ち、すっきりとした後味になる。燗酒にも向いており、日常的に楽しめる価格帯が多い。',
    body_zh: '添加少量酿造酒精的日本酒，添加量规定为白米重量10%以下。口感轻快清爽。酒精添加有助于提升香气，使后味更加爽利。适合热饮，价格亲民，适合日常享用。',
    body_en: 'A small amount of distilled alcohol is added (regulated at ≤10% of rice weight). Light, crisp, and easy-drinking. The added alcohol helps lift aromas and creates a clean finish. It is well-suited to warming and tends to be more affordable than premium grades.',
  },
  {
    term_id: 'tokubetsu-junmai',
    summary_ja: '精米歩合60%以下か特別な製法で造られた純米酒。蔵元が品質を保証する「特別」の一本。',
    summary_zh: '精米步合60%以下或采用特殊酿造方法的純米酒，由蔵元认定具备"特别"品质。',
    summary_en: 'A junmai polished to ≤60% or brewed by a special method declared by the brewery.',
    body_ja: '精米歩合60%以下か特別な製造方法で造られた純米酒。蔵元が「特別」と認める品質を持つ。純米酒と純米吟醸の中間に位置づけられることが多く、コストパフォーマンスに優れた銘柄も多い。特別な酵母や原料米を使用しているケースもある。',
    body_zh: '精米步合60%以下或采用特殊酿造方法的純米酒，由蔵元认定具有"特别"品质。常被定位于普通纯米酒与纯米吟酿之间，性价比突出。有时使用特殊酵母或原料米。',
    body_en: 'A junmai polished to 60% or less, or made by a special method declared by the brewery. Often positioned between standard junmai and junmai ginjo, these bottles frequently offer excellent value. Special yeasts or rice varieties may be used.',
  },
  {
    term_id: 'futsushu',
    summary_ja: '純米・吟醸などの「特定名称酒」に分類されない、一般的な日本酒。日本酒消費量の大部分を占める。',
    summary_zh: '未被列为特定名称酒的普通日本酒，占日本酒消费量的最大比例。',
    summary_en: 'Ordinary sake that does not qualify as any premium tokutei-meishoushu grade. The most widely consumed category.',
    body_ja: '特定名称酒に分類されない一般的な日本酒。醸造アルコールや糖類・酸味料などを添加できる。日本酒消費量の大部分を占め、価格が手頃なものが多い。地域の地酒や大手メーカーの定番品に多く、日常的な晩酌に広く親しまれている。品質の幅が広く、廉価なものから個性的なものまで様々。',
    body_zh: '未被列为特定名称酒的普通日本酒。可以添加酿造酒精、糖类、酸味料等。占日本酒消费量最大份额，价格亲民。多见于地方地酒和大型酒厂的主力产品，是日常下酒的主流选择。品质差异较大，从廉价到个性鲜明的产品均有。',
    body_en: 'Ordinary sake not classified under any premium grade. Brewing alcohol, sugars, and acidulants may be added. It accounts for the majority of sake consumed in Japan and tends to be affordable. Found in everyday dining and regional brands, quality ranges widely from simple to surprisingly characterful.',
  },
  {
    term_id: 'seimaibuai',
    summary_ja: '玄米を削って残した割合。60%なら表面40%を削り取ったことを意味し、数字が低いほど高精白。',
    summary_zh: '玄米研磨后剩余的比例。60%代表削去了40%，数值越低精白度越高。',
    summary_en: 'The percentage of the grain remaining after milling. 60% means 40% was removed. Lower = more refined.',
    body_ja: '玄米を削り残した割合。精米歩合60%なら表面40%を取り除いたことになる。外側にはたんぱく質・脂質が多く含まれ、これらが酒に雑味をもたらすため、より高精白（低い数値）にすることで繊細な香りと味わいが生まれやすくなる。吟醸は60%以下、大吟醸は50%以下が規定。',
    body_zh: '玄米研磨后剩余的比例。精米步合60%意味着去除了外侧40%。米粒外层富含蛋白质和脂肪，会给酒带来杂味。精白度越高（数值越低），酒的香气和口感越细腻。吟酿规定60%以下，大吟酿规定50%以下。',
    body_en: 'The proportion of the original brown rice grain remaining after milling. A ratio of 60% means 40% was removed. The outer layers contain proteins and fats that can add off-flavors, so higher polishing (lower numbers) yields more delicate aromas. Ginjo requires ≤60%; daiginjo requires ≤50%.',
  },
  {
    term_id: 'nihonshu-do',
    summary_ja: '日本酒の甘辛度を示す指標。＋側が辛口、－側が甘口。一般的な範囲は−5〜+10程度。',
    summary_zh: '甜辛度指标。正值为辛口（干），负值为甘口（甜），一般范围约−5到+10。',
    summary_en: 'Sweetness/dryness index. Positive = dry (karakuchi), negative = sweet (amakuchi). Typical range: −5 to +10.',
    body_ja: '日本酒の甘辛を数値で表す指標。純水と同じ比重を0とし、糖分が多いとマイナス（甘口）、少ないとプラス（辛口）になる。ただし酸度や飲み方によって体感は変わるため、あくまで目安として参考にする。+3以上を辛口、-1以下を甘口と分類することが多い。',
    body_zh: '用数值表示日本酒甜辛程度的指标。以纯水比重为基准（0），糖分多则为负值（甘口），糖分少则为正值（辛口）。但实际口感还受酸度、饮用温度等影响，仅供参考。通常+3以上为辛口，-1以下为甘口。',
    body_en: 'A numerical index for sweetness vs. dryness in sake, using pure water as the zero point. Positive values indicate dryness (less residual sugar), negative values indicate sweetness. Acidity and temperature influence the actual perceived taste, so this is a guide rather than a definitive measure. Generally +3 and above is dry; -1 and below is sweet.',
  },
  {
    term_id: 'sando',
    summary_ja: '日本酒の酸味の強さを表す数値。一般的な清酒の酸度は1.0〜2.0程度で、高いほど酸味が強い。',
    summary_zh: '日本酒酸味程度的数值指标，一般清酒约1.0～2.0，数值越高酸味越强。',
    summary_en: 'Acidity level of sake. Typical range is 1.0–2.0. Higher values mean more tartness and body.',
    body_ja: '日本酒の酸味の強さを示す数値。一般的な清酒の酸度は1.0〜2.0程度。酸度が高いほど酸味が強く感じられ、日本酒度との組み合わせで味の輪郭が変わる。酸度が高くて日本酒度がプラスなら辛口でキレがよく、酸度が低くて日本酒度がマイナスなら甘くまろやかになる傾向がある。',
    body_zh: '日本酒酸味程度的数值指标，一般清酒约1.0～2.0。酸度越高酸味越突出，与日本酒度配合决定酒的整体轮廓。酸度高且日本酒度为正值，则口感干爽有力；酸度低且日本酒度为负值，则偏甜柔和。',
    body_en: 'A measure of the total acidity in sake, typically ranging from 1.0 to 2.0. Higher acidity adds tartness and a sense of body. Combined with the SMV, it shapes the overall flavor profile: high acidity + positive SMV tends toward a dry, crisp character; low acidity + negative SMV leans sweet and mellow.',
  },
  {
    term_id: 'namazake',
    summary_ja: '加熱殺菌（火入れ）を一切行っていないフレッシュな日本酒。要冷蔵。フレッシュで活き活きとした味わい。',
    summary_zh: '未经火入（加热杀菌）处理的新鲜日本酒，需冷藏。口感鲜活生动。',
    summary_en: 'Unpasteurized sake — no heat treatment at all. Must be refrigerated. Fresh, lively, and vibrant.',
    body_ja: '加熱処理（火入れ）を一切行っていないフレッシュな日本酒。酵素が生きているため、フレッシュで活き活きとした味わいが特徴。要冷蔵で消費期限が短い。「生貯蔵酒」（瓶詰め前のみ加熱）や「生詰め酒」（瓶詰め後のみ加熱）と区別される。春の新酒シーズンに特に人気。',
    body_zh: '未经任何加热处理（火入れ）的新鲜日本酒。因酶仍具活性，口感鲜活生动为其特征。须冷藏保存，保质期较短。有别于"生贮藏酒"（仅瓶装前加热）和"生诘酒"（仅瓶装后加热）。春季新酒期间尤为受欢迎。',
    body_en: 'Sake that has undergone no heat pasteurization (hi-ire) at all. Active enzymes keep it fresh, lively, and bright. It must be refrigerated and has a shorter shelf life than pasteurized sake. Distinct from "namazume" (pasteurized only before bottling) and "namachodzo" (pasteurized only at bottling). Especially popular during the spring new-sake season.',
  },
  {
    term_id: 'genshu',
    summary_ja: '加水調整をしていない原酒。アルコール度数は17〜20度程度と高め。凝縮された味わいが特徴。',
    summary_zh: '未经加水稀释的原酒，酒精度通常约17～20度，风味浓缩集中。',
    summary_en: 'Undiluted sake — no water added after brewing. Typically 17–20% ABV with concentrated, intense flavor.',
    body_ja: '加水調整をしていない、アルコール度数の高い原酒。通常の日本酒は水を加えてアルコール度数を15〜16%に調整するが、原酒はそれをしない。17〜20%程度のアルコール度数で、味わいが凝縮されパンチがある。ロックや水割りで楽しまれることも多い。最近は15%前後の低アルコール原酒も登場。',
    body_zh: '未经加水稀释的原酒。普通日本酒会加水将酒精度调整至15～16%，而原酒不做此处理。酒精度通常达17～20%，风味浓缩有力。常以加冰或加水方式享用。近来也出现了酒精度约15%的低酒精原酒。',
    body_en: 'Sake that has not been diluted with water after brewing. While most sake is cut to about 15–16% ABV, genshu is left at its natural strength of roughly 17–20%. The result is concentrated, punchy flavor. Often enjoyed on the rocks or with water. Low-alcohol genshu around 15% has also been appearing recently.',
  },
  {
    term_id: 'kimoto',
    summary_ja: '乳酸菌を自然に取り込む伝統的な酛造り。山卸し作業が特徴。豊かな酸味と複雑な旨味が生まれる。',
    summary_zh: '通过山卸作业自然引入乳酸菌的传统酿造方式，酸味丰富，旨味复杂。',
    summary_en: 'Traditional starter (moto) made by naturally cultivating lactic acid bacteria through laborious stirring (yama-oroshi).',
    body_ja: '乳酸菌を自然に取り込む伝統的な酛（もと）造り。米・麹・水を混ぜながら「山卸し」と呼ばれる重労働で摺り潰し、乳酸菌を自然繁殖させる。雑菌の侵入を防ぎながら、豊かな酸味と複雑な旨味が生まれる。時間と手間がかかるため現在では少数の蔵が継承。独特の深みある味わいが愛好家に人気。',
    body_zh: '通过"山卸"（反复研磨搅拌）自然引入乳酸菌的传统酛酿造方式。米、麴、水边混合边用力捣磨，在防止杂菌侵入的同时让乳酸菌自然繁殖，形成丰富的酸味和复杂的旨味。工艺耗时费力，目前仅有少数酒厂坚持传承。其独特深邃的味道深受爱好者青睐。',
    body_en: 'A traditional sake starter (moto) in which lactic acid bacteria are cultivated naturally through intensive mixing called yama-oroshi (literally "mountain lowering"). The labor-intensive process guards against unwanted bacteria while producing rich acidity and complex umami. Only a small number of breweries still use this method today, and the resulting sake is prized for its depth and character.',
  },
  {
    term_id: 'yamahai',
    summary_ja: '生酛から山卸し作業を省略した製法。酸味と旨味が強く、個性的でどっしりとした味わいが生まれる。',
    summary_zh: '省略山卸作业的生酛改良版。酸味与旨味强劲，风味个性鲜明、厚重。',
    summary_en: 'A kimoto variant that skips the yama-oroshi stirring. Bold, complex, high-acid, and deeply characterful.',
    body_ja: '山卸廃止酛（やまはいもと）の略。生酛から山卸し作業を廃止した製法。乳酸菌を自然に取り込む点は生酛と同じだが、摺り潰し作業がない分、時間をかけて麹の酵素が米を溶かす。酸味と旨味が強く、個性的でどっしりとした味わいになりやすい。燗酒との相性も抜群。',
    body_zh: '山廃酛（やまはいもと）的简称，即省略山卸作业的生酛改良工艺。与生酛同样自然引入乳酸菌，但省去捣磨步骤，改由麴酶缓慢溶解米粒。酸味与旨味强劲，风味个性鲜明、厚重有力。与热酒搭配尤为出色。',
    body_en: 'Short for yamahai-moto, a variant of kimoto that eliminates the yama-oroshi stirring step. Lactic acid bacteria are still cultivated naturally, but koji enzymes slowly dissolve the rice without manual grinding. The result is bold acidity, deep umami, and a robustly characterful sake that pairs excellently with warm serving temperatures.',
  },
  {
    term_id: 'hiire',
    summary_ja: '酒を約60〜65°Cで加熱する殺菌処理。品質を安定させ、酵素の働きを止め、酒を長持ちさせる。',
    summary_zh: '将酒加热至约60～65°C进行杀菌。稳定品质、抑制酶活性，延长保存期。',
    summary_en: 'Heat pasteurization at ~60–65°C. Stabilizes the sake, halts enzyme activity, and extends shelf life.',
    body_ja: '酒を60〜65°Cで加熱する殺菌処理。酵素の働きを止め、微生物を除去し、品質を安定させる。通常は瓶詰め前と瓶詰め後の2回行う（二度火入れ）。火入れをしないものが「生酒」、1回だけのものが「生貯蔵酒」や「生詰め酒」。適切な火入れにより長期保存が可能になる。',
    body_zh: '将酒加热至60～65°C进行杀菌处理。抑制酶活性，消灭微生物，稳定酒的品质。通常在瓶装前后各进行一次（二度火入れ）。完全不火入的称"生酒"，仅做一次的有"生贮藏酒"和"生诘酒"之分。经过适当火入，酒的保存期大幅延长。',
    body_en: 'Heat pasteurization performed at approximately 60–65°C. It halts enzyme activity, eliminates microorganisms, and stabilizes the sake for long-term storage. Typically done twice — once before storage and once before bottling (nido-hiire). Sake with no pasteurization is namazake; one-time pasteurization yields either namachodzo or namazume.',
  },
  {
    term_id: 'amakuchi',
    summary_ja: '糖分が多く甘みを感じやすいスタイル。日本酒度はマイナス値が多く、飲みやすさで人気。',
    summary_zh: '含糖量高、甜味明显的日本酒风格，日本酒度多为负值，口感易于接受。',
    summary_en: 'Sweet-leaning sake style with higher residual sugar. SMV tends to be negative. Approachable and crowd-pleasing.',
    body_ja: '糖分が多く甘みを感じる日本酒のスタイル。日本酒度はマイナス値が多い。フルーティーな吟醸酒と組み合わさると、より甘く感じられることがある。辛口が好まれがちな日本では少数派だが、甘口好みの方や日本酒初心者に親しみやすい。近年は甘口クラフト日本酒も人気。',
    body_zh: '含糖量高、甜味明显的日本酒风格，日本酒度多为负值。与果香浓郁的吟酿结合时，甜味更为突出。在以辛口为主流的日本市场属少数派，但对甜口偏好者及日本酒初学者十分友好。近年甜口精酿日本酒也颇受欢迎。',
    body_en: 'A sake style with higher residual sugar and a noticeably sweet character. The SMV tends to be in negative territory. When paired with the fruity aromas of a ginjo, the sweetness can feel even more pronounced. While dry styles dominate in Japan, amakuchi sakes are approachable for newcomers and fans of sweeter drinks. Sweet craft sakes have been growing in popularity in recent years.',
  },
  {
    term_id: 'karakuchi',
    summary_ja: '糖分が少なくキレのある辛口スタイル。日本酒度はプラス値が多く、食中酒として幅広い料理に合う。',
    summary_zh: '含糖量少、口感利落的辛口风格，日本酒度多为正值，与各类料理搭配相宜。',
    summary_en: 'Dry sake style with low residual sugar and a clean finish. SMV is typically positive. Pairs well with food.',
    body_ja: '糖分が少なくキレのある辛口のスタイル。日本酒度はプラス値が多い。料理の邪魔をしない食中酒として幅広い料理と相性がよく、日本酒愛好家の中でも人気が高い。新潟の「淡麗辛口」が代表的なスタイルで、全国的に辛口が好まれる傾向がある。',
    body_zh: '含糖量少、口感利落的辛口风格，日本酒度多为正值。不喧宾夺主，与各类料理搭配相宜，深受日本酒爱好者青睐。新潟的"淡丽辛口"是其代表风格，日本整体上偏爱辛口。',
    body_en: 'Dry sake with low residual sugar and a brisk, clean finish. The SMV is typically positive. Its unobtrusive character makes it an ideal food sake that pairs with a wide range of dishes. Niigata\'s tanrei karakuchi (light and dry) style is the archetype, and dryness is the dominant preference across Japan.',
  },
  {
    term_id: 'shiboritate',
    summary_ja: '搾りたてそのまま出荷した新酒。フレッシュでフルーティー、ときに炭酸感もあるみずみずしい味わい。',
    summary_zh: '刚压榨出来即出货的新酒，口感鲜活果香突出，有时带有轻微气泡感。',
    summary_en: 'Sake shipped immediately after pressing. Fresh, fruity, sometimes lightly sparkling — sake at its youngest.',
    body_ja: '搾りたてで出荷した新鮮な日本酒。通常は搾った後に火入れ・貯蔵・加水などの工程を経るが、搾り立ては搾った直後そのまま出荷する。フレッシュでフルーティーな香りが強く、ときに微炭酸感を伴う。冬〜春にかけての新酒シーズンに楽しめる季節限定品が多い。要冷蔵。',
    body_zh: '刚压榨出来即出货的新鲜日本酒。通常压榨后还需经过火入、储藏、加水等工序，而搾りたて省略这些步骤直接上市。新鲜果香浓郁，有时带轻微气泡感。多为冬春新酒季节的限定品，须冷藏保存。',
    body_en: 'Sake shipped immediately after pressing, skipping the usual steps of pasteurization, storage, and dilution. The result is exceptionally fresh and fruity, sometimes with a slight spritz from residual CO₂. Most shiboritate are seasonal releases available from winter through spring and must be refrigerated.',
  },
  {
    term_id: 'toji',
    summary_ja: '酒蔵の醸造最高責任者。仕込み全体を指揮し、その蔵の酒の品質と個性を決定する職人。',
    summary_zh: '酒厂的酿造最高负责人。统领全部酿造工序，决定该厂酒的品质与风格。',
    summary_en: 'The master brewer who oversees all sake production at a brewery. Their skill defines the house character.',
    body_ja: '酒蔵の醸造最高責任者。仕込みの全工程を指揮し、その蔵の酒質・個性を決定する職人。かつては南部杜氏・丹波杜氏・越後杜氏など地域ごとの集団（杜氏組合）があり、季節労働者として各地の蔵に派遣されていた。現在は蔵元杜氏（オーナーが自ら杜氏を務める）も増えている。',
    body_zh: '酒厂的酿造最高负责人。统领酿造全程，决定该厂的酒质与风格。过去各地有南部杜氏、丹波杜氏、越後杜氏等地区性杜氏组织（杜氏组合），以季节工形式派遣至各地酒厂。现在蔵元杜氏（业主亲自担任杜氏）也越来越普遍。',
    body_en: 'The master brewer responsible for all sake production at a brewery. Their expertise and philosophy determine the house style. Historically, toji belonged to regional guilds (such as Nanbu Toji or Tanba Toji) and traveled as seasonal workers. Today, more brewery owners are taking on the toji role themselves (kuramototoji).',
  },
  {
    term_id: 'kuramoto',
    summary_ja: '日本酒を製造・販売する酒蔵のこと。または蔵を経営するオーナー家・企業を指す場合もある。',
    summary_zh: '酿造和销售日本酒的酒厂，有时也指经营酒厂的家族或业主。',
    summary_en: 'The sake brewery, or the family/owner that operates it. The business entity behind the sake.',
    body_ja: '日本酒を製造・販売する酒蔵のこと。または蔵を経営する家・オーナーを指す場合もある。日本全国に約1,400の蔵元が存在する。老舗の蔵元は江戸時代から続く家業も多く、地域の文化・伝統と深く結びついている。近年は若い後継者や新規参入者による革新的な蔵元も増加している。',
    body_zh: '酿造和销售日本酒的酒厂，有时也指经营酒厂的家族或业主。日本全国约有1,400家蔵元。许多老字号蔵元延续自江户时代，与地方文化传统深度交融。近年来也有越来越多年轻接班人或新入者带来革新。',
    body_en: 'The sake brewery, or the family/owner that operates it. There are approximately 1,400 kura across Japan. Many long-established kuramoto trace their lineage back to the Edo period and are deeply woven into local culture. In recent years, a new generation of brewers and entrepreneurs has been bringing fresh ideas to the industry.',
  },
  {
    term_id: 'umami',
    summary_ja: '甘・酸・塩・苦に次ぐ第五の基本味。日本酒では米由来のアミノ酸が生む深みある旨い味わい。',
    summary_zh: '第五种基本味觉。在日本酒中指米中氨基酸等产生的深厚醇美感，是风味的核心。',
    summary_en: 'The "fifth taste" — savory depth. In sake, amino acids from rice create a rich, lingering savoriness.',
    body_ja: '「美味しさ」を構成する第五の味覚。日本酒では米のグルタミン酸などが生み出す深みのある味わいを指す。旨味が強い日本酒は複雑でコクがあり、食事との相性がよい。純米酒や生酛系の日本酒に旨味が豊かなものが多い。旨味と甘みの絶妙なバランスが、日本酒の奥深さを生み出している。',
    body_zh: '构成"美味"的第五种基本味觉。在日本酒中指米中谷氨酸等氨基酸产生的深厚醇美感。旨味丰富的日本酒口感复杂醇厚，与料理搭配相宜。純米酒和生酛系日本酒中旨味尤为突出。旨味与甜味的精妙平衡，造就了日本酒的深邃魅力。',
    body_en: 'The "fifth taste" — savory depth and richness. In sake, it comes from amino acids like glutamate derived from the rice. Sakes rich in umami feel complex and full-bodied, and pair beautifully with food. Junmai and kimoto-style sakes tend to be especially high in umami. The interplay of umami and sweetness is at the heart of sake\'s depth.',
  },
  {
    term_id: 'kire',
    summary_ja: '飲み込んだ後に味が素早く消える感覚。口の中がすっきりとリセットされ、辛口の日本酒に多い特徴。',
    summary_zh: '饮后余味迅速消散、口感清爽利落。多见于辛口日本酒，使人想继续饮用。',
    summary_en: 'A clean, quick finish — taste fades rapidly after swallowing. Characteristic of dry sake.',
    body_ja: '飲み込んだ後に余韻が長引かず、口の中がすっきりする感覚。辛口の日本酒に多く見られる特徴。キレがよいと料理との相性が高まり、次の一口をすっきりと迎えることができる。酸度が高いものや、アルコール度数が高いものにキレを感じやすい。淡麗辛口スタイルのひとつの指標。',
    body_zh: '饮后余味不拖沓、口感清爽利落的感觉。多见于辛口日本酒，使与料理的搭配更为和谐，让人想接着饮用。酸度高或酒精度高的酒往往更具切れ感。是淡丽辛口风格的重要指标之一。',
    body_en: 'A clean, quick finish with little lingering aftertaste. A hallmark of dry sake. Good kire enhances food pairing — the palate is refreshed quickly, ready for the next bite. Sakes with higher acidity or alcohol content tend to feel crisper. It is a key metric in the tanrei karakuchi (light, dry) style.',
  },
]

const KEY = process.env.SUPABASE_SERVICE_ROLE_KEY
if (!KEY) { console.error('Set SUPABASE_SERVICE_ROLE_KEY'); process.exit(1) }

const { error } = await db.from('wiki_articles').upsert(articles, { onConflict: 'term_id' })
if (error) { console.error(error); process.exit(1) }
console.log(`✅ Seeded ${articles.length} wiki articles`)
