// One-shot seed for new wiki_articles rows added 2026-07 (rice/yeast/glossary gap-fill).
// Run with: node scripts/seed_wiki_2026_07.mjs

import fs from 'node:fs'

const env = fs.readFileSync('.env.local', 'utf8')
const SUPABASE_URL = env.match(/VITE_SUPABASE_URL=(.+)/)[1].trim()
const SERVICE_KEY  = env.match(/SUPABASE_SERVICE_ROLE_KEY=(.+)/)[1].trim()

const rows = [
  // ── 酒米（regional-rice） ─────────────────────────────────────────────
  { term_id: 'ginnoyume',
    summary_ja: '高知の代表酒米。「山田錦×ヒノヒカリ」で2001年登録。淡麗ながら果実系の吟醸香を引き出す。',
    summary_zhtw: '高知代表酒米。「山田錦×ヒノヒカリ」2001年品種登記。淡麗中引出果實系吟釀香。',
    summary_en: 'Kochi\'s flagship sake rice. Registered 2001 (Yamadanishiki × Hinohikari). Clean profile with fruity ginjo aromas.',
    body_ja: '高知県が「山田錦」×「ヒノヒカリ」を交配して2001年に品種登録した酒米。大粒で心白発現が良く、暖地でも安定して育つ。淡麗ながら米の甘みと旨味を素直に引き出し、フルーティーな吟醸香に向く。「土佐鶴」「酔鯨」など県内蔵のフラッグシップに採用。',
    body_zhtw: '高知縣以「山田錦」×「ヒノヒカリ」交配、2001年品種登記的酒米。粒大心白發現佳，暖地也能穩定生長。淡麗中能引出米的甘味與旨味，適合果香型吟釀香。「土佐鶴」「酔鯨」等縣內蔵之旗艦酒款採用。',
    body_en: 'A Kochi sake rice registered in 2001, bred from Yamadanishiki × Hinohikari. Large grain with reliable shinpaku, stable in warm climates. Draws out clean sweetness and umami suited to fruity ginjo aromas. Adopted by flagship Kochi breweries like Tosatsuru and Suigei.' },
  { term_id: 'tosarei',
    summary_ja: '高知の新酒米（2017年登録）。低精白でも雑味が少なく、透明感のある酒質を生む。',
    summary_zhtw: '高知新酒米（2017年登記）。低精白亦不易出雑味，能酿出透明感十足的酒質。',
    summary_en: 'A new Kochi sake rice (registered 2017). Clean, transparent character even at modest polishing.',
    body_ja: '高知県が2017年に品種登録した新しい酒造好適米。「土佐麗」の名の通り、澄んだ酒質と気品を目標に開発された。低精白でも雑味が出にくく、透明感のあるクリアな味わいを生む。県内の若手蔵元による新世代吟醸酒に多く採用されつつある。',
    body_zhtw: '高知縣2017年品種登記的新酒造好適米。以「土佐麗」為名，追求澄澈酒質與氣質而開發。低精白亦不易出雑味，能酿出透明感十足的清澈口感。縣內新世代蔵元的新型吟釀酒逐漸採用。',
    body_en: 'A newly registered (2017) Kochi sake rice bred for clarity and elegance. Even at modest polishing ratios it yields clean, transparent sake with minimal off-flavors. Increasingly used by younger Kochi brewers for next-generation ginjo styles.' },
  { term_id: 'matsuyama-mii',
    summary_ja: '愛媛の代表酒米。元は食用米、大粒で心白発達、まろやかで柔らかな酒質を生む。',
    summary_zhtw: '愛媛代表酒米。原為食用米，粒大心白發達，能酿出圓潤柔和的酒質。',
    summary_en: 'Ehime\'s signature sake rice. Originally a table rice; large grain and shinpaku yield mellow, soft-textured sake.',
    body_ja: '愛媛県の食用米として1953年に誕生し、後に酒造適性が認められた愛媛の代表酒米。大粒で心白が大きく、まろやかで柔らかな酒質を生む。「石鎚」「梅錦」「賀儀屋」など愛媛の主要蔵が積極的に使用し、県のオリジナリティを象徴する。',
    body_zhtw: '愛媛縣1953年育成的原食用米，其後被認定具酒造適性，成為愛媛代表酒米。粒大心白發達，能酿出圓潤柔和的酒質。「石鎚」「梅錦」「賀儀屋」等愛媛主要蔵積極採用，象徵縣的原創性。',
    body_en: 'Originally a table rice bred in Ehime in 1953, later recognized for brewing use — now Ehime\'s signature sake rice. Large grain and shinpaku produce mellow, soft-textured sake. Championed by leading Ehime breweries like Ishizuchi, Umenishiki, and Kagiya as an expression of local identity.' },
  { term_id: 'gin-ginga',
    summary_ja: '岩手の主力酒米（1998年登録）。耐冷性優れ、柔らかな旨味と穏やかな香りに向く。',
    summary_zhtw: '岩手主力酒米（1998年登記）。耐冷性優異，適合柔和旨味與溫和香氣。',
    summary_en: 'A cold-tolerant Iwate sake rice (registered 1998). Soft umami with gentle aromas — a Nanbu Toji staple.',
    body_ja: '岩手県が1998年に品種登録した酒造好適米。県産の「たかね錦」を親に持ち、耐冷性に優れ、寒冷地・岩手で安定した心白発現を実現。柔らかな旨味と穏やかな香りを引き出し、「南部美人」「あさ開」「浜千鳥」など県内蔵の吟醸造りに広く使われる。',
    body_zhtw: '岩手縣1998年品種登記的酒造好適米，親米為縣產「たかね錦」，耐冷性優異，在寒冷的岩手能穩定發現心白。引出柔和旨味與溫和香氣，「南部美人」「あさ開」「浜千鳥」等縣內蔵之吟釀造酒廣泛使用。',
    body_en: 'An Iwate sake rice registered in 1998, descended from local Takanenishiki. Highly cold-resistant with reliable shinpaku formation in Iwate\'s harsh climate. Yields soft umami and gentle aromas. Widely used for ginjo brewing by Nanbu Bijin, Asabiraki, Hamachidori and other Iwate breweries.' },
  { term_id: 'saito-no-shizuku',
    summary_ja: '宮崎の酒米、山田錦系。淡麗ながらしっかりした旨味と滑らかな口当たり。',
    summary_zhtw: '宮崎酒米，山田錦系。淡麗中帶紮實旨味與滑順口感。',
    summary_en: 'Miyazaki\'s sake rice, descended from Yamadanishiki. Clean yet layered with umami and a smooth mouthfeel.',
    body_ja: '宮崎県が「山田錦」を父に持つ系統から育成した酒造好適米。暖地・宮崎の気候に適応し、大粒で心白が明確。淡麗さの中にしっかりした旨味と滑らかな口当たりを生む。宮崎の「千徳」「杜氏の里」など地元蔵で使われ、南九州の日本酒アイデンティティを担う。',
    body_zhtw: '宮崎縣以「山田錦」為父系育成的酒造好適米，適應暖地宮崎氣候，粒大心白明確。淡麗中帶有紮實旨味與滑順口感。宮崎「千徳」「杜氏の里」等本地蔵使用，承擔南九州日本酒身分認同。',
    body_en: 'A Miyazaki sake rice descended from Yamadanishiki, adapted to the warm southern climate. Large grain with clear shinpaku produces sake that is clean yet layered with umami and a smooth mouthfeel. Used by local Miyazaki breweries such as Sentoku, anchoring southern Kyushu\'s sake identity.' },
  { term_id: 'isehikari',
    summary_ja: '伊勢神宮神田で1989年発見のコシヒカリ突然変異米。しっとりした甘みと落ち着いた旨味。',
    summary_zhtw: '伊勢神宮神田1989年發現的コシヒカリ突變米。濕潤甘味與沉靜旨味。',
    summary_en: 'A Koshihikari mutation discovered in 1989 at Ise Grand Shrine. Moist sweetness with quiet umami.',
    body_ja: '1989年、伊勢神宮の神田で台風後に発見されたコシヒカリの突然変異米。倒伏に強く病気にも強い神秘的な出自を持ち、神宮の御饌米として奉納される。近年、日本酒醸造用にも注目され、「白鷹」「辻本店（御前酒）」などが使用。しっとりとした甘みと落ち着いた旨味が特徴。',
    body_zhtw: '1989年在伊勢神宮神田因颱風後發現的コシヒカリ突變米。抗倒伏、抗病，帶有神秘出身，作為神宮御饌米獻上。近年也受日本酒釀造關注，「白鷹」「辻本店（御前酒）」等使用。以濕潤甘味與沉靜旨味為特徵。',
    body_en: 'A Koshihikari mutation discovered in 1989 in the sacred rice paddies of Ise Grand Shrine after a typhoon. Resistant to lodging and disease, offered as ritual rice at the shrine. Recently adopted for sake brewing by breweries like Hakutaka and Tsujihonten (Gozenshu), yielding moist sweetness and quiet umami.' },
  { term_id: 'akitsuho',
    summary_ja: '奈良の食用米。「風の森 秋津穂」で酒造用の実力を証明、ふくよかで米の旨味が強い。',
    summary_zhtw: '奈良食用米。「風の森 秋津穂」證明酒造用實力，豐潤且米之旨味強。',
    summary_en: 'A Nara table rice. "Kaze no Mori Akitsuho" proved its brewing potential — rich, rice-driven umami.',
    body_ja: '奈良県で長く栽培されてきた食用米。低アミロースで柔らかい米質。奈良・油長酒造の「風の森 秋津穂」シリーズが低精白酒母として使い、酒造好適米に劣らぬ表現力を証明した。米そのものの旨味を強く感じるふくよかな酒に仕上がる。',
    body_zhtw: '奈良縣長期栽培的食用米，低直鏈澱粉，米質柔軟。奈良油長酒造「風の森 秋津穂」系列以低精白酒母使用，證明其表現力不遜於酒造好適米。能酿出強烈感受米本身旨味的豐潤酒質。',
    body_en: 'A long-cultivated Nara table rice with low amylose and soft texture. Yucho Shuzo\'s "Kaze no Mori Akitsuho" series proved its brewing potential at low polishing ratios, delivering rich, expressive sake driven by the rice itself.' },
  { term_id: 'tosanishiki',
    summary_ja: '高知の在来酒米。栽培しやすく、しっとり素朴な味わい。地元米志向の蔵で活用される。',
    summary_zhtw: '高知在來酒米。易栽培，濕潤樸實味道。堅持本地米的蔵活用。',
    summary_en: 'A traditional Kochi sake rice. Easy to grow, moist and rustic. Still used by breweries committed to local sourcing.',
    body_ja: '高知県の在来酒造好適米で、「風鳴子」「吟の夢」以前の県産酒米として長く使われてきた。栽培しやすく、地元の食用米にも近い性格を持ち、しっとりした素朴な味わいを生む。今も高知の一部蔵で地元米使用へのこだわりとして活用される。',
    body_zhtw: '高知縣在來酒造好適米，在「風鳴子」「吟の夢」之前長期作為縣產酒米使用。栽培容易，性格接近本地食用米，能酿出濕潤樸實的味道。至今高知部分蔵仍作為堅持使用本地米的表現而活用。',
    body_en: 'A traditional Kochi sake rice used long before the arrival of Kanaruko or Ginnoyume. Easy to cultivate with characteristics close to local table rice, producing moist, homey-flavored sake. Still used by select Kochi breweries as a statement of local sourcing.' },
  { term_id: 'hitogokochi',
    summary_ja: '長野の酒米（1994年登録、美山錦×信交190号）。淡麗ですっきり、まろやかな旨味。',
    summary_zhtw: '長野酒米（1994年登記、美山錦×信交190号）。淡麗清爽，圓潤旨味。',
    summary_en: 'A Nagano sake rice (1994; Miyamanishiki × Shinko-190). Clean and dry with mellow umami.',
    body_ja: '長野県が1994年に品種登録した酒造好適米。「美山錦」×「信交190号」の交配種で、耐冷性と栽培しやすさを兼ね備える。淡麗ですっきりとした酒質を生み、まろやかで柔らかい旨味が特徴。「真澄」「大信州」「亀齢」など長野の蔵が広く使用。',
    body_zhtw: '長野縣1994年品種登記的酒造好適米，「美山錦」×「信交190号」交配種，兼具耐冷性與易栽培性。能酿出淡麗清爽的酒質，以圓潤柔和的旨味為特徵。「真澄」「大信州」「亀齢」等長野蔵廣泛使用。',
    body_en: 'A Nagano sake rice registered in 1994, from Miyamanishiki × Shinko-190. Combines cold resistance with cultivation ease. Produces clean, dry sake with mellow, gentle umami. Widely used by Nagano breweries including Masumi, Daishinshu, and Kirei.' },
  { term_id: 'hyogo-nishiki',
    summary_ja: '兵庫の新酒米（2004年登録）。山田錦系で栽培容易、心白発現良好、上品な旨味。',
    summary_zhtw: '兵庫新酒米（2004年登記）。山田錦系易栽培，心白發現良好，高雅旨味。',
    summary_en: 'A Hyogo sake rice registered in 2004, descended from Yamadanishiki. Easier to grow, with refined umami.',
    body_ja: '兵庫県が2004年に品種登録した酒造好適米。山田錦の血統を引き、山田錦より栽培しやすく、県内広域で作られる新世代の兵庫酒米。心白発現が良好で、上品な旨味とやわらかい香りの吟醸酒に仕上がる。',
    body_zhtw: '兵庫縣2004年品種登記的酒造好適米，承襲山田錦血統，比山田錦更易栽培，是兵庫縣廣域栽培的新世代酒米。心白發現良好，能酿出高雅旨味與柔和香氣的吟釀酒。',
    body_en: 'A Hyogo sake rice registered in 2004, descended from Yamadanishiki but easier to cultivate. Grown broadly across the prefecture, it offers strong shinpaku formation and produces refined ginjo with soft aromas and elegant umami.' },
  { term_id: 'tachiharuka',
    summary_ja: '九州向け暖地酒米（2010年頃登録）。高温期の登熟に強く、大粒で心白発達。',
    summary_zhtw: '九州向暖地酒米（2010年前後登記）。耐高溫期登熟，粒大心白發達。',
    summary_en: 'A warm-climate sake rice bred for Kyushu (registered around 2010). Heat-tolerant with large grain and strong shinpaku.',
    body_ja: '九州沖縄農業研究センターが暖地向けに開発した酒造好適米（2010年頃品種登録）。九州の高温期の登熟に強く、大粒で心白発達も良好。九州各県で栽培が広がり、南九州の吟醸酒シーンに新しい選択肢を提供している。',
    body_zhtw: '九州沖繩農業研究中心針對暖地開發的酒造好適米（2010年前後品種登記）。耐九州高溫期登熟，粒大心白發達。九州各縣栽培擴展中，為南九州吟釀酒場帶來新選項。',
    body_en: 'A sake rice developed by the Kyushu-Okinawa Agricultural Research Center for warm-climate cultivation (registered around 2010). Tolerates high summer temperatures at ripening, with large grain and strong shinpaku. Increasingly grown across Kyushu, offering new options for southern ginjo brewing.' },
  { term_id: 'iwai',
    summary_ja: '京都の在来酒米。1990年代以降復活栽培。柔らかく素朴な米の旨味が特徴。',
    summary_zhtw: '京都在來酒米。1990年代以後復活栽培。柔軟樸實的米之旨味為特徵。',
    summary_en: 'A native Kyoto sake rice revived from the 1990s. Soft, rustic rice umami — a Kyoto identity marker.',
    body_ja: '京都府の在来酒造好適米。戦前から栽培されたが一度絶えかけ、1990年代以降に復活栽培された歴史ある品種。柔らかく素朴な米の旨味が特徴で、京都伏見の「玉川」「澤屋まつもと」「英勲」など京都蔵に使われ、京都酒のアイデンティティを支える。',
    body_zhtw: '京都府在來酒造好適米。戰前開始栽培，曾一度斷絕，1990年代後復活栽培的歷史品種。特徵是柔和樸實的米之旨味。京都伏見的「玉川」「澤屋まつもと」「英勲」等京都蔵使用，支撐京都酒的身分認同。',
    body_en: 'A native Kyoto sake rice cultivated since prewar times; once nearly extinct, revived from the 1990s onward. Yields soft, rustic rice umami. Used by Kyoto/Fushimi breweries such as Tamagawa, Sawaya Matsumoto, and Eikun as a hallmark of Kyoto sake identity.' },
  { term_id: 'sanoto',
    summary_ja: '岩手の新世代酒米。「吟ぎんが」と並び、寒冷地で安定した心白発現が特徴。',
    summary_zhtw: '岩手新世代酒米。與「吟ぎんが」並列，寒冷地心白發現穩定為特徵。',
    summary_en: 'An Iwate new-generation sake rice alongside Ginginga. Reliable shinpaku formation in cold climates.',
    body_ja: '岩手県産の酒造好適米。「吟ぎんが」と並ぶ岩手の新世代酒米で、心白発現が安定し、寒冷地でも高品質に育つ。素朴で滋味深い旨味と柔らかい香りを生み、南部杜氏の伝統を受け継ぐ岩手の蔵元が採用している。',
    body_zhtw: '岩手縣產酒造好適米，與「吟ぎんが」並列為岩手新世代酒米。心白發現穩定，寒冷地也能高品質生長。能酿出樸實深邃的旨味與柔和香氣，繼承南部杜氏傳統的岩手蔵元採用。',
    body_en: 'An Iwate sake rice, part of the new generation alongside Ginginga. Reliable shinpaku formation and high quality even in cold climates. Delivers rustic, layered umami with soft aromas, adopted by Iwate breweries carrying on the Nanbu Toji tradition.' },
  { term_id: 'akebono',
    summary_ja: '岡山の食用米、酒造用にも古くから使用。独特のクリアな旨味と落ち着いた味わい。',
    summary_zhtw: '岡山食用米，酒造用亦自古使用。獨特清澄旨味與沉靜口感。',
    summary_en: 'An Okayama table rice long used in brewing. Uniquely clear umami and a settled character.',
    body_ja: '岡山県産の食用米で、酒造用にも古くから使われてきた。大粒でしっかりした米質を持ち、雄町の血を引かないため独特のクリアな旨味と落ち着いた味わいを生む。岡山「御前酒」「利守酒造」など地元蔵が地米へのこだわりで採用する。',
    body_zhtw: '岡山縣產食用米，自古亦作為酒造用。粒大、米質紮實，因不帶雄町血統，能酿出獨特清澄旨味與沉靜口感。岡山「御前酒」「利守酒造」等本地蔵以地米堅持而採用。',
    body_en: 'An Okayama table rice long used in brewing. Large grain with firm texture; lacking Omachi ancestry, it produces uniquely clear umami and a settled character. Used by Okayama breweries like Gozenshu and Toshimori as an expression of homegrown rice.' },
  { term_id: 'kokuryomiyako',
    summary_ja: '明治期山口の歴史的酒米。近年復活栽培され、力強い旨味と野趣ある伝統酒米らしさ。',
    summary_zhtw: '明治期山口的歷史酒米。近年復活栽培，力強旨味與野性風味。',
    summary_en: 'A Meiji-era Yamaguchi sake rice recently revived. Bold umami with the wild character of heritage varieties.',
    body_ja: '明治時代に選抜された歴史ある山口県の在来酒造好適米。かつては全国で栽培されたが、栽培難度から一時途絶。近年、山口の「澄川酒造場」「澤の鶴」などが復活栽培に成功し、力強い旨味と伝統酒米らしい野趣ある味わいの酒を生む。',
    body_zhtw: '明治時代選拔的山口縣歷史在來酒造好適米。曾遍及全國，因栽培難度一度斷絕。近年山口「澄川酒造場」「澤の鶴」等成功復活栽培，能酿出力道強勁的旨味與傳統酒米獨特的野性風味。',
    body_en: 'A historic Yamaguchi sake rice selected in the Meiji era, once cultivated nationwide but abandoned due to difficulty. Recently revived by Sumikawa Shuzo, Sawanotsuru, and others, yielding bold umami and the wild, earthy character characteristic of heritage varieties.' },
  { term_id: 'kanaruko',
    summary_ja: '高知「高育63号」。吟の夢に続く第二世代酒米、力強い旨味と芳醇な酒質。',
    summary_zhtw: '高知「高育63号」。繼吟の夢的第二世代酒米，力強旨味與芳醇酒質。',
    summary_en: 'Kochi\'s "Ko-iku 63," second-generation after Ginnoyume. Bolder umami and richer flavor.',
    body_ja: '高知県が育成した酒造好適米「高育63号」の名称。「吟の夢」に続く高知の第二世代酒米として位置づけられ、より力強い旨味と芳醇な味わいを引き出す。宇宙酵母と組み合わせた「土佐宇宙酒 完全宇宙酒」で酒米側の担当としても使用された。',
    body_zhtw: '高知縣育成的酒造好適米「高育63号」之名稱。作為「吟の夢」之後高知第二世代酒米，能引出更強勁的旨味與芳醇味道。曾在宇宙酵母結合的「土佐宇宙酒 完全宇宙酒」中作為酒米方擔當。',
    body_en: 'The name given to Kochi\'s "Ko-iku 63" sake rice — positioned as Kochi\'s second-generation variety after Ginnoyume. Draws out bolder umami and richer flavor. Notably featured on the rice side of the "Tosa Uchushu Complete Space Sake" project paired with the space yeast.' },
  { term_id: 'fukuhikari',
    summary_ja: '広く栽培される食用米。地元米志向の蔵で普通酒・本醸造の掛米に活用される。',
    summary_zhtw: '廣泛栽培的食用米。堅持本地米的蔵作為普通酒・本釀造之掛米活用。',
    summary_en: 'A widely grown table rice used as kake-mai in futsushu and honjozo by breweries emphasizing local sourcing.',
    body_ja: '広く栽培される食用米で、酒造用にも各地で使われる。米質は柔らかく、酒造好適米には分類されないが、地元米使用にこだわる蔵で普通酒や本醸造の掛米として活用される。高知県では県内産米として地元米使用の一環で採用される例がある。',
    body_zhtw: '廣泛栽培的食用米，各地也用於酒造。米質柔軟，不屬於酒造好適米，但堅持使用本地米的蔵作為普通酒或本釀造之掛米活用。高知縣有作為縣內產米在本地米堅持中採用的例子。',
    body_en: 'A widely grown table rice also used in brewing across Japan. Softer than dedicated sake rice; typically serves as kake-mai (steamed rice) in futsushu or honjozo for breweries committed to local sourcing. Occasionally featured on Kochi labels emphasizing homegrown rice.' },

  // ── 酵母（local-yeast） ─────────────────────────────────────────────
  { term_id: 'kochi-yeast',
    summary_ja: '高知の独自酵母群（AA-41・AC-17・CEL系ほか）。リンゴ酸が多く、爽やかで果実感の強い酒質。',
    summary_zhtw: '高知獨自酵母群（AA-41、AC-17、CEL系等）。蘋果酸多，清爽果實感強。',
    summary_en: 'Kochi\'s proprietary yeast family (AA-41, AC-17, CEL and more). High malic acid, vivid fruity character.',
    body_ja: '高知県醸造試験場（現・高知県工業技術センター）が独自に開発した酵母群の総称。AA-41・AC-17・AT-10などの吟醸酵母、発泡性のCEL-19やCEL-24、「かんかん丸」などバリエーションが豊富。総じてリンゴ酸を多く生成し、爽やかで果実感の強い酒質を生む。県内約17蔵が使い分け、高知の「淡麗辛口＋フルーティー」という独自ポジションを支える。',
    body_zhtw: '高知縣釀造試驗場（現高知縣工業技術中心）獨自開發的酵母群總稱。AA-41、AC-17、AT-10等吟釀酵母，發泡性CEL-19、CEL-24，「かんかん丸」等品種豐富。整體以蘋果酸產量高、酿出清爽果實感強的酒質為特徵。縣內約17蔵分別使用，支撐高知「淡麗辛口＋果香」的獨特定位。',
    body_en: 'A family of yeasts developed by the Kochi Brewing Research Institute. Includes ginjo strains like AA-41, AC-17, AT-10, sparkling strains CEL-19 and CEL-24, and specialty strains like "Kankan-Maru." Collectively produce elevated malic acid and vivid fruity character — the backbone of Kochi\'s distinctive "clean-dry-yet-fruity" identity across roughly 17 local breweries.' },
  { term_id: 'iwate-yeast',
    summary_ja: '岩手の独自酵母群。「ジョバンニの調べ」など詩情ある命名で知られる。',
    summary_zhtw: '岩手獨自酵母群。以「ジョバンニの調べ」等詩意命名聞名。',
    summary_en: 'Iwate\'s proprietary yeasts, poetically named — including "Giovanni no Shirabe."',
    body_ja: '岩手県工業技術センターが開発した独自酵母群の総称。「ゆうこの想い」（華やか吟醸系）、「ジョバンニの調べ」（宮沢賢治『銀河鉄道の夜』にちなむ、繊細で幻想的な香り）、「すず音」（発泡向け）など、詩情ある命名で知られる。南部杜氏の伝統に加え、県産酒米「吟ぎんが」「さんおと」と組み合わせて、岩手発の個性豊かな吟醸酒を生む。',
    body_zhtw: '岩手縣工業技術中心開發的獨自酵母群總稱。「ゆうこの想い」（華麗吟釀系）、「ジョバンニの調べ」（取自宮澤賢治《銀河鐵道之夜》，纖細幻想香氣）、「すず音」（發泡向）等，以詩意命名聞名。結合南部杜氏傳統與縣產酒米「吟ぎんが」「さんおと」，酿出岩手獨特個性的吟釀酒。',
    body_en: 'A family of yeasts developed by the Iwate Industrial Research Institute. Includes "Yuko no Omoi" (bright ginjo character), "Giovanni no Shirabe" (named after Miyazawa Kenji\'s Night on the Galactic Railroad — delicate, dreamlike aromas), and "Suzune" for sparkling styles. Combined with Nanbu Toji brewing tradition and local rice varieties, they define Iwate\'s poetic sake voice.' },
  { term_id: 'yamaguchi-9e',
    summary_ja: '山口の吟醸酵母。9号系で豊富なカプロン酸エチル、キレの良い吟醸香。獺祭も併用。',
    summary_zhtw: '山口吟釀酵母。9號系豐富己酸乙酯，爽利吟釀香。獺祭亦併用。',
    summary_en: 'A Yamaguchi ginjo yeast derived from Kyokai No. 9. Abundant ethyl caproate with crisp aromas — blended with 1801 by Dassai.',
    body_ja: '山口県産業技術センターが選抜育成した吟醸酵母。協会9号系から派生した株で、カプロン酸エチルを豊富に生成しつつ酸が穏やか、キレの良い吟醸香を持つ。「獺祭」が協会1801号と併用することで知られ、「東洋美人」「雁木」など県内蔵も採用。山口が「吟醸大国」として世界に躍り出た立役者の一つ。',
    body_zhtw: '山口縣產業技術中心選拔育成的吟釀酵母。從協會9號系派生的酵母株，能豐富產生己酸乙酯同時酸度溫和，具備爽利吟釀香。「獺祭」以其與協會1801號併用聞名，「東洋美人」「雁木」等縣內蔵也採用。是山口作為「吟釀大國」躍上世界舞台的功臣之一。',
    body_en: 'A ginjo yeast selectively bred by the Yamaguchi Industrial Technology Center. Derived from the Kyokai No. 9 lineage, it delivers abundant ethyl caproate with restrained acidity and crisp ginjo aromas. Famously blended with Kyokai No. 1801 in Dassai brewing, and used by Toyobijin, Gangi, and other Yamaguchi breweries powering the region\'s global ginjo profile.' },
  { term_id: 'kyoto-yeast',
    summary_ja: '京都府オリジナル酵母。バナナ・洋梨系の柔らかい香りと京料理に寄り添う穏やかな酸。',
    summary_zhtw: '京都府原創酵母。香蕉、洋梨系柔和香氣，貼近京料理的溫和酸味。',
    summary_en: 'A Kyoto original yeast. Soft banana- and pear-like aromas with quiet acidity that suits Kyoto cuisine.',
    body_ja: '京都府農林水産技術センターが開発した京都府オリジナル酵母。バナナ・洋梨系の柔らかい吟醸香と、京料理に寄り添う穏やかで上品な酸味が特徴。伏見の蔵元を中心に、京都産酒米「祝」との組み合わせで京都テロワールを表現する試みに使われる。',
    body_zhtw: '京都府農林水產技術中心開發的京都府原創酵母。以香蕉、洋梨系柔和吟釀香，以及貼近京料理的溫和高雅酸味為特徵。伏見蔵元為中心，與京都產酒米「祝」搭配，用於表現京都風土的嘗試。',
    body_en: 'A proprietary Kyoto yeast developed by the Kyoto Agricultural Technology Center. Soft banana- and pear-like ginjo aromas with restrained, elegant acidity that pairs with Kyoto cuisine. Used mainly by Fushimi breweries — often together with the Kyoto rice "Iwai" — as an expression of Kyoto terroir.' },
  { term_id: 'ringo-san-kobo',
    summary_ja: 'リンゴ酸を大量生成する特殊酵母群。白ワイン風の酸味、低アル・食中酒向け。',
    summary_zhtw: '大量產生蘋果酸的特殊酵母群。白酒風酸味，低酒精・佐餐酒向。',
    summary_en: 'Specialty yeasts that produce abundant malic acid. White-wine-like acidity for low-alcohol, food-friendly sake.',
    body_ja: '通常の酵母より数倍〜十数倍のリンゴ酸を生成する特殊酵母の総称。爽やかで白ワインを思わせる酸味を生み、低アルコール・食中酒向けの日本酒に用いられる。福島県開発の「うつくしま煌酵母」、静岡・山梨など複数の県が独自株を持ち、CEL-24などスパークリング系にも共通する性質。',
    body_zhtw: '產生比一般酵母高數倍至十數倍蘋果酸的特殊酵母總稱。能酿出清爽、令人聯想到白酒的酸味，用於低酒精・佐餐向的日本酒。福島縣開發的「うつくしま煌酵母」，靜岡・山梨等多縣皆有獨自酵母株，也與CEL-24等發泡系共通此特性。',
    body_en: 'A family of specialty yeasts that produce several to over ten times the malic acid of standard strains. Yields crisp, white-wine-like acidity — used for low-alcohol, food-friendly sake. Fukushima\'s "Utsukushima Kirameki," Shizuoka and Yamanashi strains all belong here; the property is also shared by CEL-24 and other sparkling yeasts.' },

  // ── 用語集（glossary） ─────────────────────────────────────────────
  { term_id: 'kura-tsuki-kobo',
    summary_ja: '酒蔵に自然に住み着く野生酵母群。その蔵だけの味を生み、自然派・生酛系で重視される。',
    summary_zhtw: '酒蔵自然棲息的野生酵母群。酿出該蔵獨有的味道，自然派・生酛系重視。',
    summary_en: 'Wild yeasts naturally inhabiting a brewery. Produce a unique "sound of the house" — central to natural and kimoto brewing.',
    body_ja: '酒蔵の建物・設備に自然に住み着いている野生酵母群の総称。長年同じ蔵で酒を醸すうちに、その蔵に適応した独自の酵母群が形成される。協会酵母のような均一な発酵は難しいが、他の蔵では再現できない「その蔵だけの味」を生む。生酛・山廃系や無添加醸造で重視され、「新政」の6号酵母もかつては蔵付酵母だった。',
    body_zhtw: '酒蔵建築與設備上自然棲息的野生酵母群總稱。同一蔵長年釀酒的過程中，會形成適應該蔵的獨自酵母群。難以像協會酵母那樣均勻發酵，但能酿出其他蔵無法重現的「該蔵獨有的味道」。生酛・山廃系與無添加釀造重視此類酵母，「新政」6號酵母亦曾是蔵付酵母。',
    body_en: 'The community of wild yeasts naturally inhabiting a brewery\'s building and equipment. Over generations of brewing, each kura develops its own adapted yeast community. Less predictable than Kyokai yeasts, but produces a "sound of the house" no other brewery can replicate. Central to kimoto/yamahai and additive-free brewing — Aramasa\'s Kyokai No. 6 originated as a house yeast.' },
  { term_id: 'kobo-mutenka',
    summary_ja: '培養酵母を添加せず、蔵付酵母のみで発酵する醸造法。生酛系・自然派の代表。',
    summary_zhtw: '不添加培養酵母，僅以蔵付酵母發酵的釀造法。生酛系・自然派代表。',
    summary_en: 'A method that adds no cultured yeast — fermentation relies on house yeasts. A signature of kimoto and natural sake.',
    body_ja: '培養酵母を添加せず、蔵付酵母や酒母中に自然に増殖する酵母のみで発酵させる醸造法。生酛・山廃系との組み合わせが多く、発酵の主導権を微生物の自然な生態系に委ねる。予測しづらいが、複雑で個性的な味わいと蔵の風土を反映した酒が生まれる。近年の自然派・クラシック系ムーブメントの代表的キーワード。',
    body_zhtw: '不添加培養酵母，僅以蔵付酵母或酒母中自然增殖之酵母進行發酵的釀造法。多與生酛・山廃系搭配，將發酵主導權交給微生物的自然生態系。難以預測，但能酿出複雜個性的味道，反映蔵之風土。近年自然派・復古系運動的代表關鍵字。',
    body_en: 'A brewing method that adds no cultured yeast — fermentation relies on the house yeasts already present in the brewery or that naturally proliferate in the moto. Typically paired with kimoto or yamahai. Yields unpredictable but complex, terroir-driven sake, and stands as a signature keyword of the natural/classic sake movement.' },
  { term_id: 'shirokoji',
    summary_ja: '本来焼酎用のクエン酸生成麹菌。「新政 亜麻猫」等で日本酒にも活用、爽やかな酸味。',
    summary_zhtw: '原本燒酎用之檸檬酸生成麴菌。「新政 亜麻猫」等日本酒亦活用，清爽酸味。',
    summary_en: 'A citric-acid-producing koji originally for shochu. Popularized by Aramasa\'s "Amaneko" — brings crisp acidity to sake.',
    body_ja: '本来は焼酎造りに用いられる麹菌 Aspergillus kawachii（アワモリ黒麹菌の白色変異株）。日本酒の一般的な黄麹と比べクエン酸を大量に生成するため、爽やかで白ワインのような酸味を持つ新感覚の日本酒が造れる。「新政 亜麻猫」を筆頭に、近年一部の革新系蔵元が黄麹と併用して独自の酒質を追求している。',
    body_zhtw: '原本用於燒酎釀造的麴菌 Aspergillus kawachii（泡盛黑麴菌之白色變異株）。與日本酒常用之黃麴相比，能大量產生檸檬酸，可酿出清爽如白酒般酸味的新感覺日本酒。「新政 亜麻猫」為首，近年部分革新系蔵元將其與黃麴併用，追求獨特酒質。',
    body_en: 'A koji mold (Aspergillus kawachii) traditionally used in shochu — a white mutation of the black koji used for awamori. Compared to sake\'s standard yellow koji, it produces abundant citric acid, enabling crisp, white-wine-like sake. Aramasa\'s "Amaneko" popularized its use; a handful of innovative breweries now blend it with yellow koji to craft distinctive new styles.' },
]

;(async () => {
  const now = new Date().toISOString()
  const payload = rows.map(r => ({ ...r, updated_at: now }))
  const res = await fetch(`${SUPABASE_URL}/rest/v1/wiki_articles?on_conflict=term_id`, {
    method: 'POST',
    headers: {
      apikey: SERVICE_KEY,
      Authorization: `Bearer ${SERVICE_KEY}`,
      'Content-Type': 'application/json',
      Prefer: 'resolution=merge-duplicates,return=representation',
    },
    body: JSON.stringify(payload),
  })
  const text = await res.text()
  if (!res.ok) {
    console.error('FAILED', res.status, text.slice(0, 500))
    process.exit(1)
  }
  const data = JSON.parse(text)
  console.log(`✓ Upserted ${data.length} rows`)
  console.log('term_ids:', data.map(r => r.term_id).join(', '))
})()
